language: go

on:
  push:
    branches:
      - master
      - feature-v2.0.0

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - "1.17"
  - "1.18"
  - "1.19"
  - "1.20"
  - "1.21"

install: 
  - go get github.com/karldoenitz/Tigo/TigoWeb
